name: newsfeed_multiple_imageview
description: Facebook type multiple news feed images view.
version: 1.0.0
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  transparent_image: ^2.0.0
  flutter_image_slideshow: ^0.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic

  assets:
    - assets/
    - assets/fonts/